### ISSUE TITLE
Issue with Unichart Generating Redundant Words in Non-4.28.1 Transformers 

### ISSUE THREAD

**Issue by Ryoo72** [tingxueronghua/ChartLlama-code#10]
I read your interesting research with great interest. Thank you for conducting such excellent work. I have a minor question to ask. I noticed in the paper that it's mentioned, "Unichart will generate meaningless redundant words when the output is too long." I've found that Unichart functions correctly only with the Transformers version 4.28.1, and when using versions other than this, it tends to produce redundant words. I'm curious to know if the Unichart version was set to 4.28.1 in your setup.

**Comment by tingxueronghua** [comment]
Directly use the demo provided could verify the phenomenon.

As I remember, I use transformers==4.31.0. But I found in most cases the output is meaningful. 

And what do the word "correctly" mean? Does this mean Unichart will work totally wrong when the transformers are in a different version? I do not observe such a phenomenon in my machine.
