### ISSUE TITLE
Hyperparameters for training your model on Chart2Text train dataset

### ISSUE THREAD

**Issue by y-rok** [tingxueronghua/ChartLlama-code#13]
Hello. 

In your research paper, you mentioned that you trained ChartLlama on the train split when evaluating using BLEU-4.
Can you tell me what hyper-parameters you used to train the model for Chart2text? (e.g. epochs, batch size...)

Thanks in advance :)

**Comment by tingxueronghua** [comment]
I use the same training hyperparameters except the epochs as 10 for pew and 3 for statistas, as I remember. In fact I do not have much time for choosing the hyperparameters, and I think you can try more to get higher performances.
