### ISSUE TITLE
About a new chart dataset in Chinese.

### ISSUE THREAD

**Issue by SWHL** [tingxueronghua/ChartLlama-code#19]
Thanks for your great work. 
I just wonder whether to have a plan for creating and opening source a new chart dataset in Chinese?

Thanks.

**Comment by tingxueronghua** [comment]
I think it is hard. One reason is that both CLIP and Llama are hard to understand Chinese. Maybe Qwen-VL is more appropriate for this purpose?

**Comment by SWHL** [comment]
Thanks
