### ISSUE TITLE
why the derender result is exactly the same as the input in fig.1

### ISSUE THREAD

**Issue by LightDXY** [tingxueronghua/ChartLlama-code#4]
Hi authors, thanks for your amazing work, I have a question.
In fig.1, why the derender result is exactly the same as the input?
 
![image](https://github.com/tingxueronghua/ChartLlama-code/assets/18134953/ce462508-fb81-40cc-9d0e-b4aca6a369d0)

**Comment by tingxueronghua** [comment]
hi, this figure is just for illustration. You can refer to the qualitative results in our paper. We will add notifications.
