### ISSUE TITLE
how to download model weight

### ISSUE THREAD

**Issue by mengdongwei** [tingxueronghua/ChartLlama-code#5]
Great job! I saw in the update log that the model weight file has been released, but I can't find where to download the model weight file.

**Comment by tingxueronghua** [comment]
Hi, thanks for attention to our work!
Here is the link for the Lora weights. https://huggingface.co/listen2you002/ChartLlama-13b
But I am busy these days and the model weights can just be downloaded manually.
Remember to use our model_vqa_lora.py to load the model, and maybe you need to change the path in the config.json of the model. (I forgot to change the vision tower path)

**Comment by mengdongwei** [comment]
Thanks !

**Comment by sarth1110** [comment]
Hi, could someone please help which file is considered as LORA checkpoint. I am attaching the hugging face repo that I am able to view for the project. Please let me know if there is an alternate place where I could find the checkpoints. Thank you
![Screenshot from 2024-04-10 16-33-08](https://github.com/tingxueronghua/ChartLlama-code/assets/65600339/c156ae93-e595-4f2b-9f00-4e070552fb83)
