### ISSUE TITLE
About the results in Table 2.

### ISSUE THREAD

**Issue by Sootung** [tingxueronghua/ChartLlama-code#6]
Hello，It is a great job. I have few questions.
Are the Metrics for Chart extraction in Table 2 the RMS precision and RMS F1 mentioned in DePlot? Additionally，It seems that DePlot does not perform the Chart extraction task on the ChartQA dataset. Are the results of this part (chart extraction, including the Chart extraction of Unichart) reproduced by you yourself? Are these the results of fine-tuning on the ChartQA dataset using DePlot and Unichart?

**Comment by tingxueronghua** [comment]
Yes, their model weights are all open source, so I reproduce the results using their model.

**Comment by tingxueronghua** [comment]
Forget to confirm. They did not show performances on ChartQA in their paper.
Also, there is something that deserves attention. I did not study the metrics in details. But I found if using wrong seperator, the performance will become extremely high... So pay attention to it. Our seperator is ",", while previous methods are usually "|".

Feel free to reopen this issue if you have any other questions.

**Comment by Sootung** [comment]
> Forget to confirm. They did not show performances on ChartQA in their paper. Also, there is something that deserves attention. I did not study the metrics in details. But I found if using wrong seperator, the performance will become extremely high... So pay attention to it. Our seperator is ",", while previous methods are usually "|".
> 
> Feel free to reopen this issue if you have any other questions.

Thanks for your response.
