### ISSUE TITLE
Where can I get the weights~~

### ISSUE THREAD

**Issue by LJQbiu** [tingxueronghua/ChartLlama-code#7]
Where can I get the weights~~

**Comment by tingxueronghua** [comment]
Here~~
https://huggingface.co/listen2you002/ChartLlama-13b
I should mark it more obviously... I will change the readme as soon as I have some time.

**Comment by LJQbiu** [comment]
Thank you very much~^_^~



| |
李江权
|
|
***@***.***
|
---- Replied Message ----
| From | Yucheng ***@***.***> |
| Date | 12/13/2023 21:40 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [tingxueronghua/ChartLlama-code] Where can I get the weights~~ (Issue #7) |

Here~~
https://huggingface.co/listen2you002/ChartLlama-13b
I should mark it more obviously... I will change the readme as soon as I have some time.
