### ISSUE TITLE
Any plan to open-source the generated chart data?

### ISSUE THREAD

**Issue by zfj1998** [tingxueronghua/ChartLlama-code#9]
Thanks to the authors for your excellent work! I am also exploring tabular data generation with LLMs. So, I'd like to know whether you plan to open-source the intermediate data when generating chart data. Thanks again, keep up the good work.(●'◡'●)

**Comment by tingxueronghua** [comment]
Thanks for your interest in our work! I am also cleaning the training data and I hope it could be released as soon as possible. As for the quality of the generated data, detailed information could be referred to in this issue:

https://github.com/tingxueronghua/ChartLlama-code/issues/8

Feel free to reopen this issue if you still have any questions :)

**Comment by bhosalems** [comment]
Is the cleaning process complete yet?
